Enforce -release 8, close #417 (#418)
Motivation:

Release 3.9.0 is not compatible with Java 8 because it was compile with Java 9+ without enforcing `-release` option.
As a result, bytecode is linked to the new ByteBuffer methods introduced in Java 9 that overload the ones defined in Buffer.
This causes better-files 3.9.0 to crash with NoSuchMethodErrors when running with Java 8.

Modification:

Enforce -release 8 when sbt runs with Java 9+.

Result:

sbt build now generates bytecode compatible with Java 8, whatever the runtime version (as long as code is compatible).